# Generated by Django 3.2.6 on 2021-09-07 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('github_profiles_app', '0003_repository'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repository',
            old_name='num_start',
            new_name='num_star',
        ),
    ]
